services:
  - type: web
    name: weather-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: WEATHER_API_KEY
        sync: false
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
    healthCheckPath: /
    autoDeploy: true
    branch: main